APP/urls.py
from django.urls import path
from APP import views

urlpatterns = [
    path('', views.index, name="index"),
    path("index/", views.index, name="index"),
    path('login/', views.login, name='login'),
    path('check_login/', views.check_login, name='check_login'),
    path('register/', views.register, name='register'),
    path('check_register/', views.check_register, name='check_register'),
    path('logout/', views.logout, name="logout"),
    path('all_dishes/', views.all_dishes, name="all_dishes"),
    path('data_visualization/', views.data_visualization, name="data_visualization"),
    path('guess_youlike/', views.guess_youlike, name="guess_youlike"),
    path("like/<str:food_name>/<str:operate>", views.like),
    path("food_drink/", views.food_drink, name="food_drink"),
    path("food_staple/", views.food_staple, name="food_staple"),
    path("food_dishes/", views.food_dishes, name="food_dishes"),
    path("food_dessert/", views.food_dessert, name="food_dessert"),
    path("search/", views.search, name="search"),
    path("food_single/", views.food_single, name="food_single"),
    path("all_user/", views.all_user, name="all_user"),
    path("add_image/", views.add_image, name="add_image"),
    path("receive_image/", views.receive_image, name="receive_image"),

]

djangoProject4/urls.py
from django.contrib import admin
from django.urls import path, include
from APP import views

urlpatterns = [
    # 直接使用跟路由
    # path('', views.index),
    # path('book/', views.book),
    # path('book/detail/<book_id>/', views.book_detail),
    # path('book/author/detail/', views.author_detail)

    # 使用子路由（一个应用对应一个子路由）命名空间namespace（可以解决屌用时有多个重名html问题）
    path('', include(('APP.urls', 'APP'), namespace='APP')),

    path('admin/', admin.site.urls),
]

templates/all_dishes.html
{% load my_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="../static/js/all_dishes.js"></script>
    <script src="../static/js/jquery-3.5.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/all_dishes.css">
    <title>所有菜品展览</title>
        <!-- 加载图标库以在小屏幕上显示汉堡菜单（栏） -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

<!-- 创建一个导航栏容器 -->
<div class="navbar" id="myNavbar">
  <!-- 创建一个链接列表 -->
  <ul class="navlist">
    <!-- 创建一个越南美食推荐系统的文字 -->
    <li><span class="recommend">越南美食推荐系统</span></li>
    <!-- 创建一个链接到所有菜品展览的链接 -->
    <li><a href="{% url 'APP:all_dishes' %}">所有菜品展览<hr></a></li>
      <li><a href="{% url 'APP:food_drink' %}" class="daughter_element">饮品</a></li>
      <li><a href="{% url 'APP:food_staple' %}" class="daughter_element">主食</a></li>
      <li><a href="{% url 'APP:food_dishes' %}" class="daughter_element">菜品</a></li>
      <li><a href="{% url 'APP:food_dessert' %}" class="daughter_element">甜点</a></li>
    <!-- 创建一个链接到数据可视化的链接 -->
    <li><a href="{% url 'APP:data_visualization' %}">数据可视化</a></li>
    <!-- 创建一个链接到所有用户喜欢列表的链接 -->
    <li><a href="{% url 'APP:all_user' %}">喜欢列表</a></li>
    <!-- 创建一个链接到猜您喜欢的链接 -->
    <li><a href="{% url 'APP:guess_youlike' %}">猜您喜欢</a></li>
      {% if Administrator %}
            <!-- 上传文件 -->
        <li><a href="{% url 'APP:add_image' %}">添加美食</a></li>
      {% endif %}
  </ul>
  <!-- 创建一个登录信息区域 -->
  <div class="login-info">
    <!-- 如果用户已登录，显示用户名 -->
      {% if user_name %}
          <span id="username">您好，{{ user_name }}&nbsp<a href="{% url 'APP:logout' %}" style="color: white">退出登录</a></span>
      {% else %}
          <span id="username"><a href="{% url 'APP:login' %}" style="color: white">请先登录</a></span>
      {% endif %}

  </div>
  <!-- 创建一个图标，用于在小屏幕上打开和关闭导航栏 -->
  <a href="javascript:void(0);" class="icon" onclick="toggleNavbar()">
    <i class="fa fa-bars"></i>
  </a>
</div>

{#搜索功能#}
<!-- 创建一个容器，设置最大宽度为600px，居中显示 -->
<div class="container2">
  <!-- 创建一个搜索框，使用search-box类来实现自定义的样式 -->
  <div class="search-box">
    <!-- 创建一个输入框，使用search-input类来实现自定义的样式，设置placeholder属性为请输入搜索内容 -->
    <input type="search" id="search-input" class="search-input" placeholder="请输入搜索内容">
    <!-- 创建一个图标，使用search-icon类来实现自定义的样式，添加onclick属性为search()，表示点击时调用search函数 -->
    <span class="search-icon" onclick="search()">&#128269;</span>
  </div>
</div>
<div class="container">
    <ul class="list">
    {% for food_name, food_path in items %}
        <li class="item">
        <!-- 添加一个flip-box容器 -->
        <div class="flip-box">
            <!-- 添加一个flip-box-inner容器 -->
            <div class="flip-box-inner">
                <!-- 添加一个flip-box-front容器，放置图片 -->
                <div class="flip-box-front">
                    <img src="{{ food_path }}" class="image_food">
                    <span class="name">{{ food_name }}</span>
                    {% if food_name in like_food_list %}
                        <span class="like active" data-id="{{ food_name }}">❤</span>
                    {% else %}
                        <span class="like" data-id="{{ food_name }}">❤</span>
                    {% endif %}
                </div>
                <!-- 添加一个flip-box-back容器，放置文字 -->
                <div class="flip-box-back">
                    <p>{{ food_introduction|get_item:food_name }}</p>
                </div>
            </div>
        </div>
        </li>
    {% endfor %}
    </ul>
</div>


</body>
</html>

templates/all_user.html
{% load my_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="../static/js/all_user.js"></script>
    <script src="../static/js/jquery-3.5.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/all_user.css">
    <link rel="stylesheet" type="text/css" href="../static/css/food_single.css">
    <title>喜欢列表</title>
    <!-- 加载图标库以在小屏幕上显示汉堡菜单（栏） -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

<!-- 创建一个导航栏容器 -->
<div class="navbar" id="myNavbar">
    <!-- 创建一个链接列表 -->
    <ul class="navlist">
        <!-- 创建一个越南美食推荐系统的文字 -->
        <li><span class="recommend">越南美食推荐系统</span></li>
        <!-- 创建一个链接到所有菜品展览的链接 -->
        <li><a href="{% url 'APP:all_dishes' %}">所有菜品展览</a></li>
        <!-- 创建一个链接到数据可视化的链接 -->
        <li><a href="{% url 'APP:data_visualization' %}">数据可视化</a></li>
        <!-- 创建一个链接到所有用户喜欢列表的链接 -->
        <li><a href="{% url 'APP:all_user' %}">喜欢列表
            <hr>
        </a></li>
        <!-- 创建一个链接到猜您喜欢的链接 -->
        <li><a href="{% url 'APP:guess_youlike' %}">猜您喜欢</a></li>
    </ul>
    <!-- 创建一个登录信息区域 -->
    <div class="login-info">
        <!-- 如果用户已登录，显示用户名 -->
        {% if user_name %}
            <span id="username">您好，{{ user_name }}&nbsp<a href="{% url 'APP:logout' %}"
                                                            style="color: white">退出登录</a></span>
        {% else %}
            <span id="username"><a href="{% url 'APP:login' %}" style="color: white">请先登录</a></span>
        {% endif %}

    </div>
    <!-- 创建一个图标，用于在小屏幕上打开和关闭导航栏 -->
    <a href="javascript:void(0);" class="icon" onclick="toggleNavbar()">
        <i class="fa fa-bars"></i>
    </a>
</div>

<div class="container">
    <div class="header">
        <ul class="nav">
            <li><h2>{{ user_name }}</h2></li>
        </ul>
    </div>
    <div class="main">
        {% for food_name,food_path in items %}
            <div class="card">
                <img src="{{ food_path }}" alt="{{ food_name }}"> <!-- 这里是美食的图片 -->
                <h3>{{ food_name }}</h3> <!-- 这里是美食的名称 -->
                <p>{{ food_introduction|get_item:food_name }}</p> <!-- 这里是美食的简介 -->
                {% if food_name in like_food_list %}
                    <span class="like active" data-id="{{ food_name }}">❤</span>
                {% else %}
                    <span class="like" data-id="{{ food_name }}">❤</span>
                {% endif %}
            </div>
        {% endfor %}

    </div>
</div>
</body>
</html>

templates/food_dessert.html
{% load my_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="../static/js/all_dishes.js"></script>
    <script src="../static/js/jquery-3.5.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/all_dishes.css">
    <title>甜点</title>
        <!-- 加载图标库以在小屏幕上显示汉堡菜单（栏） -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

<!-- 创建一个导航栏容器 -->
<div class="navbar" id="myNavbar">
  <!-- 创建一个链接列表 -->
  <ul class="navlist">
    <!-- 创建一个越南美食推荐系统的文字 -->
    <li><span class="recommend">越南美食推荐系统</span></li>
    <!-- 创建一个链接到所有菜品展览的链接 -->
    <li><a href="{% url 'APP:all_dishes' %}">所有菜品展览<hr></a></li>
      <li><a href="{% url 'APP:food_drink' %}" class="daughter_element">饮品</a></li>
      <li><a href="{% url 'APP:food_staple' %}" class="daughter_element">主食</a></li>
      <li><a href="{% url 'APP:food_dishes' %}" class="daughter_element">菜品</a></li>
      <li><a href="{% url 'APP:food_dessert' %}" class="daughter_element">甜点<hr></a></li>
    <!-- 创建一个链接到数据可视化的链接 -->
    <li><a href="{% url 'APP:data_visualization' %}">数据可视化</a></li>
    <!-- 创建一个链接到所有用户喜欢列表的链接 -->
    <li><a href="{% url 'APP:all_user' %}">喜欢列表</a></li>
    <!-- 创建一个链接到猜您喜欢的链接 -->
    <li><a href="{% url 'APP:guess_youlike' %}">猜您喜欢</a></li>
  </ul>
  <!-- 创建一个登录信息区域 -->
  <div class="login-info">
    <!-- 如果用户已登录，显示用户名 -->
      {% if user_name %}
          <span id="username">您好，{{ user_name }}&nbsp<a href="{% url 'APP:logout' %}" style="color: white">退出登录</a></span>
      {% else %}
          <span id="username"><a href="{% url 'APP:login' %}" style="color: white">请先登录</a></span>
      {% endif %}

  </div>
  <!-- 创建一个图标，用于在小屏幕上打开和关闭导航栏 -->
  <a href="javascript:void(0);" class="icon" onclick="toggleNavbar()">
    <i class="fa fa-bars"></i>
  </a>
</div>

{#搜索功能#}
<!-- 创建一个容器，设置最大宽度为600px，居中显示 -->
<div class="container2">
  <!-- 创建一个搜索框，使用search-box类来实现自定义的样式 -->
  <div class="search-box">
    <!-- 创建一个输入框，使用search-input类来实现自定义的样式，设置placeholder属性为请输入搜索内容 -->
    <input type="search" id="search-input" class="search-input" placeholder="请输入搜索内容">
    <!-- 创建一个图标，使用search-icon类来实现自定义的样式，添加onclick属性为search()，表示点击时调用search函数 -->
    <span class="search-icon" onclick="search()">&#128269;</span>
  </div>
</div>

<div class="container">
    <ul class="list">
    {% for food_name, food_path in items %}
        <li class="item">
        <!-- 添加一个flip-box容器 -->
        <div class="flip-box">
            <!-- 添加一个flip-box-inner容器 -->
            <div class="flip-box-inner">
                <!-- 添加一个flip-box-front容器，放置图片 -->
                <div class="flip-box-front">
                    <img src="{{ food_path }}" class="image_food">
                    <span class="name">{{ food_name }}</span>
                    {% if food_name in like_food_list %}
                        <span class="like active" data-id="{{ food_name }}">❤</span>
                    {% else %}
                        <span class="like" data-id="{{ food_name }}">❤</span>
                    {% endif %}
                </div>
                <!-- 添加一个flip-box-back容器，放置文字 -->
                <div class="flip-box-back">
                    <p>{{ food_introduction|get_item:food_name }}</p>
                </div>
            </div>
        </div>
        </li>
    {% endfor %}
    </ul>
</div>


</body>
</html>

templates/food_dishes.html
{% load my_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="../static/js/all_dishes.js"></script>
    <script src="../static/js/jquery-3.5.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/all_dishes.css">
    <title>菜品</title>
        <!-- 加载图标库以在小屏幕上显示汉堡菜单（栏） -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

<!-- 创建一个导航栏容器 -->
<div class="navbar" id="myNavbar">
  <!-- 创建一个链接列表 -->
  <ul class="navlist">
    <!-- 创建一个越南美食推荐系统的文字 -->
    <li><span class="recommend">越南美食推荐系统</span></li>
    <!-- 创建一个链接到所有菜品展览的链接 -->
    <li><a href="{% url 'APP:all_dishes' %}">所有菜品展览<hr></a></li>
      <li><a href="{% url 'APP:food_drink' %}" class="daughter_element">饮品</a></li>
      <li><a href="{% url 'APP:food_staple' %}" class="daughter_element">主食</a></li>
      <li><a href="{% url 'APP:food_dishes' %}" class="daughter_element">菜品<hr></a></li>
      <li><a href="{% url 'APP:food_dessert' %}" class="daughter_element">甜点</a></li>
    <!-- 创建一个链接到数据可视化的链接 -->
    <li><a href="{% url 'APP:data_visualization' %}">数据可视化</a></li>
    <!-- 创建一个链接到所有用户喜欢列表的链接 -->
    <li><a href="{% url 'APP:all_user' %}">喜欢列表</a></li>
    <!-- 创建一个链接到猜您喜欢的链接 -->
    <li><a href="{% url 'APP:guess_youlike' %}">猜您喜欢</a></li>
  </ul>
  <!-- 创建一个登录信息区域 -->
  <div class="login-info">
    <!-- 如果用户已登录，显示用户名 -->
      {% if user_name %}
          <span id="username">您好，{{ user_name }}&nbsp<a href="{% url 'APP:logout' %}" style="color: white">退出登录</a></span>
      {% else %}
          <span id="username"><a href="{% url 'APP:login' %}" style="color: white">请先登录</a></span>
      {% endif %}

  </div>
  <!-- 创建一个图标，用于在小屏幕上打开和关闭导航栏 -->
  <a href="javascript:void(0);" class="icon" onclick="toggleNavbar()">
    <i class="fa fa-bars"></i>
  </a>
</div>

{#搜索功能#}
<!-- 创建一个容器，设置最大宽度为600px，居中显示 -->
<div class="container2">
  <!-- 创建一个搜索框，使用search-box类来实现自定义的样式 -->
  <div class="search-box">
    <!-- 创建一个输入框，使用search-input类来实现自定义的样式，设置placeholder属性为请输入搜索内容 -->
    <input type="search" id="search-input" class="search-input" placeholder="请输入搜索内容">
    <!-- 创建一个图标，使用search-icon类来实现自定义的样式，添加onclick属性为search()，表示点击时调用search函数 -->
    <span class="search-icon" onclick="search()">&#128269;</span>
  </div>
</div>

<div class="container">
    <ul class="list">
    {% for food_name, food_path in items %}
        <li class="item">
        <!-- 添加一个flip-box容器 -->
        <div class="flip-box">
            <!-- 添加一个flip-box-inner容器 -->
            <div class="flip-box-inner">
                <!-- 添加一个flip-box-front容器，放置图片 -->
                <div class="flip-box-front">
                    <img src="{{ food_path }}" class="image_food">
                    <span class="name">{{ food_name }}</span>
                    {% if food_name in like_food_list %}
                        <span class="like active" data-id="{{ food_name }}">❤</span>
                    {% else %}
                        <span class="like" data-id="{{ food_name }}">❤</span>
                    {% endif %}
                </div>
                <!-- 添加一个flip-box-back容器，放置文字 -->
                <div class="flip-box-back">
                    <p>{{ food_introduction|get_item:food_name }}</p>
                </div>
            </div>
        </div>
        </li>
    {% endfor %}
    </ul>
</div>


</body>
</html>

templates/food_drink.html
{% load my_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="../static/js/all_dishes.js"></script>
    <script src="../static/js/jquery-3.5.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/all_dishes.css">
    <title>饮品</title>
        <!-- 加载图标库以在小屏幕上显示汉堡菜单（栏） -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

<!-- 创建一个导航栏容器 -->
<div class="navbar" id="myNavbar">
  <!-- 创建一个链接列表 -->
  <ul class="navlist">
    <!-- 创建一个越南美食推荐系统的文字 -->
    <li><span class="recommend">越南美食推荐系统</span></li>
    <!-- 创建一个链接到所有菜品展览的链接 -->
    <li><a href="{% url 'APP:all_dishes' %}">所有菜品展览<hr></a></li>
      <li><a href="{% url 'APP:food_drink' %}" class="daughter_element">饮品<hr></a></li>
      <li><a href="{% url 'APP:food_staple' %}" class="daughter_element">主食</a></li>
      <li><a href="{% url 'APP:food_dishes' %}" class="daughter_element">菜品</a></li>
      <li><a href="{% url 'APP:food_dessert' %}" class="daughter_element">甜点</a></li>
    <!-- 创建一个链接到数据可视化的链接 -->
    <li><a href="{% url 'APP:data_visualization' %}">数据可视化</a></li>
    <!-- 创建一个链接到所有用户喜欢列表的链接 -->
    <li><a href="{% url 'APP:all_user' %}">喜欢列表</a></li>
    <!-- 创建一个链接到猜您喜欢的链接 -->
    <li><a href="{% url 'APP:guess_youlike' %}">猜您喜欢</a></li>
  </ul>
  <!-- 创建一个登录信息区域 -->
  <div class="login-info">
    <!-- 如果用户已登录，显示用户名 -->
      {% if user_name %}
          <span id="username">您好，{{ user_name }}&nbsp<a href="{% url 'APP:logout' %}" style="color: white">退出登录</a></span>
      {% else %}
          <span id="username"><a href="{% url 'APP:login' %}" style="color: white">请先登录</a></span>
      {% endif %}

  </div>
  <!-- 创建一个图标，用于在小屏幕上打开和关闭导航栏 -->
  <a href="javascript:void(0);" class="icon" onclick="toggleNavbar()">
    <i class="fa fa-bars"></i>
  </a>
</div>

{#搜索功能#}
<!-- 创建一个容器，设置最大宽度为600px，居中显示 -->
<div class="container2">
  <!-- 创建一个搜索框，使用search-box类来实现自定义的样式 -->
  <div class="search-box">
    <!-- 创建一个输入框，使用search-input类来实现自定义的样式，设置placeholder属性为请输入搜索内容 -->
    <input type="search" id="search-input" class="search-input" placeholder="请输入搜索内容">
    <!-- 创建一个图标，使用search-icon类来实现自定义的样式，添加onclick属性为search()，表示点击时调用search函数 -->
    <span class="search-icon" onclick="search()">&#128269;</span>
  </div>
</div>

<div class="container">
    <ul class="list">
    {% for food_name, food_path in items %}
        <li class="item">
        <!-- 添加一个flip-box容器 -->
        <div class="flip-box">
            <!-- 添加一个flip-box-inner容器 -->
            <div class="flip-box-inner">
                <!-- 添加一个flip-box-front容器，放置图片 -->
                <div class="flip-box-front">
                    <img src="{{ food_path }}" class="image_food">
                    <span class="name">{{ food_name }}</span>
                    {% if food_name in like_food_list %}
                        <span class="like active" data-id="{{ food_name }}">❤</span>
                    {% else %}
                        <span class="like" data-id="{{ food_name }}">❤</span>
                    {% endif %}
                </div>
                <!-- 添加一个flip-box-back容器，放置文字 -->
                <div class="flip-box-back">
                    <p>{{ food_introduction|get_item:food_name }}</p>
                </div>
            </div>
        </div>
        </li>
    {% endfor %}
    </ul>
</div>


</body>
</html>

templates/food_staple.html
{% load my_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="../static/js/all_dishes.js"></script>
    <script src="../static/js/jquery-3.5.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/css/all_dishes.css">
    <title>主食</title>
        <!-- 加载图标库以在小屏幕上显示汉堡菜单（栏） -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

<!-- 创建一个导航栏容器 -->
<div class="navbar" id="myNavbar">
  <!-- 创建一个链接列表 -->
  <ul class="navlist">
    <!-- 创建一个越南美食推荐系统的文字 -->
    <li><span class="recommend">越南美食推荐系统</span></li>
    <!-- 创建一个链接到所有菜品展览的链接 -->
    <li><a href="{% url 'APP:all_dishes' %}">所有菜品展览<hr></a></li>
      <li><a href="{% url 'APP:food_drink' %}" class="daughter_element">饮品</a></li>
      <li><a href="{% url 'APP:food_staple' %}" class="daughter_element">主食<hr></a></li>
      <li><a href="{% url 'APP:food_dishes' %}" class="daughter_element">菜品</a></li>
      <li><a href="{% url 'APP:food_dessert' %}" class="daughter_element">甜点</a></li>
    <!-- 创建一个链接到数据可视化的链接 -->
    <li><a href="{% url 'APP:data_visualization' %}">数据可视化</a></li>
    <!-- 创建一个链接到所有用户喜欢列表的链接 -->
    <li><a href="{% url 'APP:all_user' %}">喜欢列表</a></li>
    <!-- 创建一个链接到猜您喜欢的链接 -->
    <li><a href="{% url 'APP:guess_youlike' %}">猜您喜欢</a></li>
  </ul>
  <!-- 创建一个登录信息区域 -->
  <div class="login-info">
    <!-- 如果用户已登录，显示用户名 -->
      {% if user_name %}
          <span id="username">您好，{{ user_name }}&nbsp<a href="{% url 'APP:logout' %}" style="color: white">退出登录</a></span>
      {% else %}
          <span id="username"><a href="{% url 'APP:login' %}" style="color: white">请先登录</a></span>
      {% endif %}

  </div>
  <!-- 创建一个图标，用于在小屏幕上打开和关闭导航栏 -->
  <a href="javascript:void(0);" class="icon" onclick="toggleNavbar()">
    <i class="fa fa-bars"></i>
  </a>
</div>

{#搜索功能#}
<!-- 创建一个容器，设置最大宽度为600px，居中显示 -->
<div class="container2">
  <!-- 创建一个搜索框，使用search-box类来实现自定义的样式 -->
  <div class="search-box">
    <!-- 创建一个输入框，使用search-input类来实现自定义的样式，设置placeholder属性为请输入搜索内容 -->
    <input type="search" id="search-input" class="search-input" placeholder="请输入搜索内容">
    <!-- 创建一个图标，使用search-icon类来实现自定义的样式，添加onclick属性为search()，表示点击时调用search函数 -->
    <span class="search-icon" onclick="search()">&#128269;</span>
  </div>
</div>

<div class="container">
    <ul class="list">
    {% for food_name, food_path in items %}
        <li class="item">
        <!-- 添加一个flip-box容器 -->
        <div class="flip-box">
            <!-- 添加一个flip-box-inner容器 -->
            <div class="flip-box-inner">
                <!-- 添加一个flip-box-front容器，放置图片 -->
                <div class="flip-box-front">
                    <img src="{{ food_path }}" class="image_food">
                    <span class="name">{{ food_name }}</span>
                    {% if food_name in like_food_list %}
                        <span class="like active" data-id="{{ food_name }}">❤</span>
                    {% else %}
                        <span class="like" data-id="{{ food_name }}">❤</span>
                    {% endif %}
                </div>
                <!-- 添加一个flip-box-back容器，放置文字 -->
                <div class="flip-box-back">
                    <p>{{ food_introduction|get_item:food_name }}</p>
                </div>
            </div>
        </div>
        </li>
    {% endfor %}
    </ul>
</div>


</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>登录页面</title>
    <link rel="stylesheet" type="text/css" href="../static/css/login.css">
</head>
<body>
    <div class="box">
        <span class="borderLine"></span>
        <form action="{% url 'APP:check_login' %}" method="post">
            {% csrf_token %}
          <h2>登录</h2>
          <div class="inputBox">
            <input type="text" required name="user_name">
            <span >用户名</span><i></i>
          </div>
          <div class="inputBox">
            <input type="password" required name="user_password">
            <span>密码</span><i></i>
          </div>
            {% if error %}
                <p style="color: red"><i>用户名或密码错误</i><p>
            {% endif %}
          <div class="links">
            <a href="#">忘记密码？</a><a href="{% url 'APP:register' %}">注册</a>
          </div>
          <input type="submit" value="登录">
        </form>
      </div>
</body>
</html>